import Head from "next/head";
import Logo from "../components/logo";
import Button from "../components/button";
import ImageCard from "../components/image-card";

import restaurantOriginal from "../public/images/restaurant-original.png";
import restaurantDrawing from "../public/images/restaurant-drawing.png";
import dishOriginal from "../public/images/dish-original.png";
import dishDrawing from "../public/images/dish-drawing.png";
import SplashScreen from "../components/splash-screen";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next.js Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SplashScreen />

      <div className="root">
        <header>
          <div className="header-content">
            <Logo />
            <Button secondary>Contact</Button>
          </div>
        </header>

        <main>
          <section className="intro-section">
            <div className="section-text-content">
              <h1>Lorem ipsum dolor sit amet consectetur</h1>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione, repellendus dolores natus adipisci
                doloribus magnam quia sunt laudantium non. Error ea impedit in eos unde cum incidunt ullam consequatur
                qui.
              </p>
              <Button>Make a Reservation</Button>
            </div>
            <ImageCard drawingImg={restaurantDrawing} originalImage={restaurantOriginal} />
          </section>

          <section className="about-section">
            <h2>About</h2>
            <div className="about-section__content">
              <ImageCard drawingImg={dishDrawing} originalImage={dishOriginal} />
              <div className="section-text-content">
                <h3>Our Story</h3>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse, similique non corporis fugiat
                  laboriosam est enim reiciendis, aspernatur ad nostrum voluptatum. Impedit non voluptatum ea rem ut
                  facere exercitationem minima!
                </p>
                <Button>Contact Us</Button>
              </div>
            </div>
          </section>
        </main>

        <footer>
          <p>© 2022 Copyright. Lorem ipsum.</p>
        </footer>
      </div>
    </div>
  );
}
